[package]
name = "PiXr"
version = "0.1.0"
authors = ["Sebastian Richter <sebastian.richter@paessler.com>"]
edition = "2018"

[lib]
name = "PiXr"

[dependencies]
sdl2 = "0.32"
rmp-serde = "1.1"
serde = { version = "1.0", features = ["derive"] }
